quasar_database_url = "postgres://postgres:postgres@localhost:5432/quasar_development"

[ingestion]
polling_interval = 5

[api]
host = "127.0.0.1"
port = 8080
depth_limit = 3
complexity_limit = 16

[metrics]
database_polling_interval = 5
